---
title: GUIDE INSTALLER
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
gems:
- jekyll-feed
- jekyll-gist
- jekyll-redirect-from
- jekyll-seo-tag
color: "#228ae6"
exclude:
- CNAME
- README.md
- NOTES.md
- LICENSE.md
- ".gitignore"
- package.json
- bower.json
- _js
- _scss
- gulpfile.js
- gulpconfig.js
- node_modules
- bower_components
- gemfile
permalink: "/:title/"
tagline: UWC Docs is a documentation website for the UWC WordPress theme.
keywords: documentation, wordpress, theme, uwc, jekyll
description: UWC Docs is a documentation website for the UWC WordPress theme.
url: https://sadapwebid.github.io
baseurl: "/guide-installer"
logo: "/assets/icons/apple-icon-144x144.png"
twitter:
  username: connor_baer
google_analytics_key: UA-37412525-6
google_site_verification: p5kLTD8qj2E2-ScnrDnltQoqY_MLqN0QW3hlk5N4qYQ
author:
  org: Made by Connor.
  name: Connor Bär
  url: https://sadapwebid.github.io
  email: hi@madebyconnor.io
  twitter: connor_baer
version: 1.1.0
github:
  repo: https://github.com/uwc/uwc-docs
google_fonts:
  Source Sans Pro: 400, 600, 700
  Source Code Pro: 
